docs/AWS/EKS/reference/retention-policy.md
=> refactor(eks): rename deletion policy to retention policy

.github/workflows/deploy-pages.yaml
Moving docs to sphinx based workflow.
In the meantime, we want to keep deploying
the old docs.
=> Build old-main

.github/workflows/build.yml
That way, docs are build for each PR and the result can be seen.
=> Add github action to build and store the artifact

aws/eks/eks-how-to/deploy-ubuntu-pro-cluster.rst
Modify the ua client by the pro client. Change the order of the section with and without fips because without fips is the more used, and merge the two eksctl config file sections into one.
=> feat(eks): refactoring EKS documentation

.wordlist.txt, aws/aws-how-to/eks-gpu-enablement.rst, aws/aws-how-to/index.rst
GPU is supported in eks and document
step-by-step how to enable for users.
=> feat(eks): enable gpu in eks

oci/oci-how-to/create-chiselled-ubuntu-image.rst
Since we released Chisel binary, let's use it in this tutorial
=> Refactor: Use chisel binary

aws/aws-how-to/aws-marketplace-identifiers.csv
Mantic listings are available. Add
identifiers for user to search those
listings.
=> feat: Add Mantic listings

.wordlist.txt, aws/aws-how-to/index.rst, aws/aws-how-to/instances/index.rst, aws/aws-how-to/instances/install-nvidia-drivers.rst
Added page, updated indexes and added words to the spelling corrector
=> adding Nvidia drivers on AWS

google/google-explanation/canonical-offerings.rst
Moved links to the bottom of the page for easy maintenance and consistency
=> [google] Minor updates to Canonical's offerings page

google/google-explanation/canonical-offerings.rst
Added references to secure boot, SEV-capable, SEV-SNP, Intel TDX, signed Nvidia drivers, CVE fixing and the close collaboration between Canonical and Google.
=> Adding confidential compute references and other text mods

.wordlist.txt, aws/aws-how-to/instances/create-ec2-using-ubuntu-image.rst, aws/aws-how-to/instances/index.rst, aws/aws-reference/ec2-credentials.rst, aws/aws-reference/index.rst, aws/index.rst
Wiki page[0] has not been updated since
2014 and refresh the page with correct
information.
Refs: [0] https://help.ubuntu.com/community/EC2StartersGuide
[1] https://warthogs.atlassian.net/browse/CPC-2015
=> docs: Redo AWS EC2 Starters Guide

.wordlist.txt, all-clouds/all-clouds-explanation/confidential-computing.rst, all-clouds/index.rst, azure/azure-explanation/confidential-computing.rst, azure/azure-explanation/image-rentention-policy.rst, azure/azure-explanation/index.rst, google/google-explanation/canonical-offerings.rst, google/google-explanation/confidential-computing.rst, google/google-explanation/gce-image-retention-policy.rst, reuse/common-intro.txt
[all-clouds] move explanation for confidential computing from specific clouds to all-clouds
=> [Google] reorganise image retention policy content

aws/aws-how-to/index.rst, aws/aws-how-to/instances/index.rst, aws/aws-how-to/instances/upgrade-to-ubuntupro-with-license-manager.rst, aws/conf.py
Tutorials to upgrade LTS to Pro with using AWS systems manager and License manager
=> docs(aws): Document upgrade Ubuntu LTS to Pro with License manager

aws/aws-how-to/instances/find-ubuntu-images.rst
Add available version to be searchable for focal
so reader don't confuse this sentence.
=> fix(eks): Rephrase EKS version for focal build

.custom_wordlist.txt, aws/aws-how-to/index.rst, aws/aws-how-to/instances/automatically-setup-multiple-nics.rst, aws/aws-how-to/instances/index.rst
Co-authored-by: Dimple Kuriakose <dimple.kuriakose@canonical.com>
=> feat(aws): doc automatic setup of multi-NIC instances

all-clouds/index.rst, aws/index.rst, azure/index.rst, google/index.rst
For files:
azure/index.rst
all-clouds/index.rst
google/index.rst
aws/index.rst
Fixed the padding for the diatxis grids.
=> Fixing grid padding to improve text alginment for some index.rst pages.

readme.rst
Public cloud: Update readme with links to per project contribution guidelines #40
=> #40 updated README.rst

aws/aws-how-to/instances/find-ubuntu-images.rst, aws/aws-how-to/instances/launch-ubuntu-ec2-instance.rst
=> [AWS]Add explanation for launching instances using --image-id resolve:ssm

azure/azure-how-to/instances/get-ubuntu-pro.rst
We need at least 30 sec before the IMDS licenceType is updated
=> azure: Update the process of in-place upgrade

azure/azure-how-to/instances/find-ubuntu-images.rst
@k-dimple  fixes https://github.com/canonical/open-documentation-academy/issues/51
=> edit ODA-51

aws/aws-how-to/instances/build-pro-ami-using-packer.rst
Adding the current caveats for using packer with newer Ubuntu versions
=> Updating packer instructions

aws/aws-explanation/eks-snaps.rst, aws/aws-explanation/index.rst
This adds a brief explanation of what snaps we bundle in the EKS image and why
=> feat: add eks snaps explanation

ibm/ibm-how-to/find-ubuntu-images.rst, ibm/ibm-how-to/launch-ubuntu-instances.rst, ibm/index.rst
Still need to test out the CLI instructions... Will put this out of WIP/Draft once I'm sure all the tutorials are sane.
=> Adding ibm

aws/aws-explanation/ec2-image-retention-policy.rst
Clarify the policy on unlaunched images and how they will be handled.
=> docs(aws): Update AWS image retention policy

azure/azure-how-to/instances/find-ubuntu-images.rst
Removes Mantic from the doc for finding Ubuntu images on Azure.
=> feat(azure): Remove EOL Mantic release

azure/azure-how-to/instances/find-ubuntu-images.rst
Publication of Azure Pro CVM for Jammy and Noble has been completed.
=> Azure pro cvm noble jammy

public-images/public-images-how-to/index.rst, public-images/public-images-how-to/use-local-cloud-init-ds.rst
Refs:
- https://warthogs.atlassian.net/browse/CPC-4698
=> docs: add section on local cloud-init dataource

aws/aws-how-to/instances/launch-and-attest-amd-sev-snp-instances.rst
changed the installation of rust to the rustup snap
=> Added rustup snap

.custom_wordlist.txt, .readthedocs.yaml, all-clouds/all-clouds-explanation/ubuntu-base-and-minimal-images.rst, public-images/public-images-how-to/launch-qcow-with-qemu.rst, public-images/public-images-how-to/run-an-ova-using-virtualbox.rst, public-images/public-images-how-to/use-local-cloud-init-ds.rst
and remove spelling check failures
[CI] Include spelling check for all sub-projects
=> [public-images] Minor updates to ensure style consistency 

.custom_wordlist.txt, oracle/oracle-how-to/deploy-oke-nodes-using-ubuntu-images.rst, oracle/oracle-how-to/index.rst
OKE LA has specific instructions for how to pull the image and use it when creating different kinds of k8s nodes.
=> feat(oke): Create OKE nodes with Ubuntu images.

.custom_wordlist.txt, public-images/public-images-how-to/index.rst, public-images/public-images-how-to/launch-with-libvirt.rst
How to find images.
How to launch them from the terminal.
How to launch them using uvt.
Refs: [0] https://warthogs.atlassian.net/browse/CPC-4695
=> feat(public-images): how-to launch using libvirt

azure/azure-how-to/instances/find-ubuntu-images.rst
Add the newly published SKUs for 18.04, 20.04, 22.04 and 24.04.
=> feat(azure): Add Pro server ARM64 SKUs

aws/aws-explanation/index.rst, aws/aws-explanation/ubuntu-security-on-aws.rst
Adding security overview page for AWS EC2.
=> feat: AWS security overview

.custom_wordlist.txt, all-clouds/all-clouds-explanation/cloud-init-metapackages.rst, all-clouds/index.rst
=> feat(all-clouds): add docs on cloud-init metapackages

aws/aws-how-to/instances/upgrade-to-ubuntu-pro-at-scale-using-tokens-with-ssm.rst, aws/aws-how-to/kubernetes/enable-gpus-on-eks.rst, azure/azure-how-to/kubernetes/install-kubeflow-on-aks.rst
Addresses issues [#281](https://github.com/canonical/ubuntu-cloud-docs/issues/281) and [#282](https://github.com/canonical/ubuntu-cloud-docs/issues/282).
=> [AWS] Update instructions for enabling GPUs on EKS. 

aws/aws-how-to/instances/aws-marketplace-identifiers.csv
Add EKS 1.31 marketplace codes.
=> feat: EKS 1.31 marketplace listing identifiers

azure/azure-how-to/instances/find-ubuntu-images.rst
We should be able to merge this today but the offer is still publishing, so please don't merge for now.
Also, while doing this I noticed the following issues:
1. Since we had no interim release currently being supported, the paragraph was empty but the title was still there which was confusing
2. We do not document our minimal images anywhere! Including for Noble that has a unified offer with both server and minimal. We should fix it at least for Noble.
=> azure/how-to: add Oracular offer and fix links to Chinese Marketplace

aws/aws-how-to/index.rst, aws/aws-how-to/kubernetes/deploy-ubuntu-cluster-with-eks-ami.rst, aws/aws-how-to/kubernetes/index.rst
Create tutorial about how to deploy ubuntu EKS
cluster and modify index to include tutorial
with similar topic.
=> fix: Tutorial to deploy ubuntu EKS Cluster

aws/aws-reference/pro.rst, aws/aws-reference/support.rst
Also move some links into a separate section
=> Change formatting to avoid a spelling check error

public-images/public-images-explanation/index.rst, public-images/public-images-explanation/ubuntu-security-on-public-images.rst
Added a security overview for images available at cloud-images.ubuntu.com
=> docs(download): Add Security section for public images

all-clouds/all-clouds-how-to/index.rst, all-clouds/index.rst, aws/aws-how-to/index.rst, aws/index.rst, azure/azure-how-to/index.rst, azure/index.rst, google/google-how-to/index.rst, google/index.rst, ibm/ibm-how-to/index.rst, ibm/index.rst, oracle/index.rst, oracle/oracle-how-to/enable-confidential-computing.rst, oracle/oracle-how-to/index.rst, oracle/oracle-how-to/upgrade-from-focal-to-jammy.rst, oracle/oracle-how-to/upgrade-from-jammy-to-noble.rst
and some minor style corrections for 'Enable CC' guide
=> [Oracle] Update the landing page for how-to guides 

docs/google/google-explanation/canonical-offerings.rst, docs/google/google-how-to/gce/upgrade-in-place-from-lts-to-pro.rst
=> Cleanup20250728

docs/google/google-explanation/security-overview.rst, docs/google/google-how-to/gce/create-different-instance-types.rst
(1) security overview page and
(2) create instances page
=> [GCP] Update two pages related to launching CVMs and pointing to Pro

docs/oracle/oracle-explanation/ubuntu-on-oke-worker-nodes.rst, docs/oracle/oracle-how-to/deploy-ubuntu-oke-nodes-using-console.rst, docs/oracle/oracle-how-to/index.rst, docs/oracle/oracle-reference/ubuntu-availability-on-oke.rst
Renamed the title 'Deploy Ubuntu OKE nodes using Console' to 'Deploy Ubuntu OKE nodes using Oracle Cloud Console' for better understanding to end users.
=> (Oracle): Rename title to include 'Oracle Cloud Console'
