canonical/ubuntu-cloud-docs

- mkdocs.yml
By default, mkdocs assumes that the default branch is master and not
main. This is fixed here.
[0] https://www.mkdocs.org/user-guide/configuration/#edit_uri
> mkdocs: fix edit_uri to point to main branch

- README.md
That's useful to quickly find the rendered version of the docs.
> Add github pages link to README

- .wordlist.txt
- readme.rst
The doc is now deployed on readthedocs, we can add a link to the readme.
> Add link to doc in readme

- conf.py
With that, the documentation title does no longer contain "0.1". That information doesn't belong to the title and 0.1 doesn't help at all anyway.
Dropping the variable does adjust the title[0].
Refs:
- [0] https://pradyunsg.me/furo/customisation/sidebar-title/
> fix: drop release from conf.py

- azure/azure-how-to/install-azure-cli.rst
We were still downloading the repository key in trusted.gpg.d which is unsafe.
> fix(azure): use /etc/apt/keyrings to add new repository

- azure/azure-explanation/daily-vs-release-images.rst
The intersphinx reference (in 'azure') only works after the external project ('all-clouds') is published.
> Add reference to all-clouds/release-types in Azure image types.

- google/google-explanation/canonical-offerings.rst
Removing references in customer-facing documentation to the kernel and guest pipelines, that are purely for CPC internal use, and the Anthos-on-Bare-Metal product in which Ubuntu is "under the hood" and not publicly visible.
> Removing GCP references to pipelines that are not externally visible

- google/google-explanation/canonical-offerings.rst
Updates to tighten the text in some areas, and to include explicit references to ARM (Tau) support and links to Google's Anthos-on-VMware, Anthos-on-AWS and Anthos-on-Azure ref docs.
> Tightening text and adding Anthos URL refs

- google/google-explanation/gce-image-retention-policy.rst
- google/google-explanation/index.rst
We have recently implemented a deletion policy, which is a change from the norm where all images were just stored. This commit details where we will start deleting old images and gives a brief decription of deprecation as well.
> feat(GCE): Add docs describing image deletion and deprecation

- aws/aws-how-to/instances/find-ubuntu-images.rst
This updates the EKS reference path to show how to find images for EKS 1.29+ and images for <1.29
> fix: update eks ssm paths to illustrate eks 1.29+

- .wordlist.txt
- azure/azure-explanation/confidential-computing.rst
- azure/azure-how-to/index.rst
- azure/azure-how-to/instances/index.rst
- azure/azure-how-to/instances/launch-ubuntu-images.rst
Per [0], created dedicated documentation for launching Ubuntu CVM images on Azure. Given there was no documentation for launching Ubuntu images on Azure in general, de-duplicated the Azure CLI launch instructions for Trusted Launch in the confidential computing document. Also refined the Azure CLI commands as it applies to Trusted Launch (e.g. selecting the TrustedLaunch security type will automatically enable vTPM).
Also normalized proper noun capitalization for references to Trusted Launch and Confidential Virtual Machines. Although the capitalization in Azure documentation can also be inconsistent at times, given these security features are discretely named (Standard, Trusted Launch, and Confidential Virtual Machine) - distinguishing them from regular prose aids readability. …
> docs(azure): azure cvm and trusted launch revisions

- aws/aws-how-to/instances/find-ubuntu-images.rst
Let user know EKS 1.29 images can be
found on Focal and Jammy.
> fix(aws): Support EKS 1.29 on Focal

- aws/aws-how-to/instances/find-ubuntu-images.rst
This updates the docs to specify that gp3 is used in VOL_TYPE in ssm parameter paths for ubuntu images based on mantic or newer.
> docs(aws-ssm): volume type gp3 in >=23.10

- conf.py
- custom_conf.py
This pull request solves [issue #28 of the open-documentation-academy repository](https://github.com/canonical/open-documentation-academy/issues/28).
I added configuration to the base `conf.py` file to disable tabs closing.
> Disable Sphinx tabs closing

- all-clouds/all-clouds-how-to/check-cve-on-instance.rst
All CVE OVAL data from ESM repositories and the archives has been consolidated into one file since 15th Feb 2024. This was earlier published as separate files for each repository and the archive. Thus, we longer need instructions to merge the OVAL files before running a scan.
The commit also includes some wording changes in the Check CVE doc.
Tests
1. Instructions under `Scan the instance` worked on a GCP focal instance.
2. Verified that local render looks good using `make serve`.
3. `make woke` reported no findings.
4. `make spelling` reported some false positives.
> fix: Remove OVAL feed merging in check CVE docs

- .custom_wordlist.txt
- .wordlist.txt
- all-clouds/all-clouds-how-to/contribute-to-these-docs.rst
- aws/aws-how-to/contribute-to-these-docs.rst
- azure/azure-how-to/contribute-to-these-docs.rst
- google/google-how-to/contribute-to-these-docs.rst
- ibm/ibm-how-to/contribute-to-these-docs.rst
- oci/oci-how-to/contribute-to-these-docs.rst
- oracle/oracle-how-to/contribute-to-these-docs.rst
- reuse/contribute-to-docs.txt
This pull request improves the [clarity of the reuse/contribute-to-docs.txt](https://github.com/canonical/ubuntu-cloud-docs/blob/main/reuse/contribute-to-docs.txt) file and adds instructions on how to create new documentation pages and categories. It also includes instructions on the files to update after creating new pages and categories, solving [issue #41 of the Open Documentation Academy repository](https://github.com/canonical/open-documentation-academy/issues/41).
> I used the manual list numbering in the "Creating new categories" subsection because the numbering defaults back to one after the block code showing the structure of a toctree.
> Public cloud: Add instructions on how to create new files and categories

- google/google-how-to/gce/upgrade-in-place-from-lts-to-pro.rst
In preparing for noble release, I noticed that we do not have jammy listed on the LTS-to-pro upgrade path documentation.
> fix(gce): Add jammy to list of upgrade URIs

- .gitignore
- all-clouds/index.rst
- aws/aws-how-to/instances/find-ubuntu-images.rst
- custom_conf.py
- oci/conf.py
- oci/index.rst
- oci/links.txt
- oci/oci-explanation/index.rst
- oci/oci-explanation/ubuntu-oci-container.rst
- oci/oci-explanation/ubuntu-pro-oci-container.rst
- oci/oci-how-to/contribute-to-these-docs.rst
- oci/oci-how-to/create-chiselled-ubuntu-image.rst
- oci/oci-how-to/deploy-pro-container-on-pro-kubernetes-cluster.rst
- oci/oci-how-to/enable-pro-services.rst
- oci/oci-how-to/getting-started.rst
- oci/oci-how-to/index.rst
- oci/oci-reference/index.rst
- oci/oci-reference/oci-image-configuration.rst
- oci/oci-tutorials/fips-ubuntu-container.rst
- oci/oci-tutorials/index.rst
- readme.rst
This PR includes:
- a refactoring of the Ubuntu OCI docs, including titles and navigation
- enforcement of the diataxis framework to the docs
- additional guides and tutorials, some reused from other docs, to complete the information
> docs: restructure and apply diataxis to OCI docs

- all-clouds/conf.py
- aws/conf.py
- azure/conf.py
- custom_conf.py
- google/conf.py
- ibm/conf.py
- oci/conf.py
- oracle/conf.py
Although canonical-internal links are of debatable value for public-facing docs, it can still be useful for internal feedback.
This changes the link to the internal-public channel as the eng channel is invite-only.
> fix: Point to internal-public mattermost channel.

- .custom_wordlist.txt
- all-clouds/all-clouds-explanation/ubuntu-base-and-minimal-images.rst
- all-clouds/index.rst
This adds a brief explanation for Ubuntu Base and Minimal images. And what the `unminimize` command does.
This can, of course, be improved. But this is just the first iteration.
> Add explanation for Ubuntu Base and Minimal images

- .custom_wordlist.txt
- all-clouds/index.rst
- custom_conf.py
- public-images/index.rst
- public-images/public-images-explanation/index.rst
- public-images/public-images-how-to/build-vagrant-with-bartender.rst
- public-images/public-images-how-to/index.rst
- public-images/public-images-how-to/run-a-vagrant-box.rst
1. Remove explanation section since currently it only has 1 topic
2. Update the generic descriptions to specify Vagrant since currently that is the only image we are talking about
3. Correct some minor typos
4. Include pointers to public images and OCI registries in the main public cloud page
> [public images] Minor reorganisation

- public-images/public-images-how-to/build-vagrant-with-bartender.rst
Should be a double dash for the `name` arg when adding a vagrant box.
`--name BOX                   Name of the box`
> Update build-vagrant-with-bartender.rst with missing dash

- aws/aws-explanation/ec2-image-retention-policy.rst
Change the example for EOSS to Bionic Beaver since Jammy still under support and it can confuse reader.
> fix(aws): fix the example to reduce confusion

- azure/azure-how-to/instances/launch-ubuntu-images.rst
We want our users to prefer noble or jammy instead of focal which is now 4 years old.
> azure-how-to: replace focal by noble

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
That includes EKS and EKS-Pro.
> feat(aws): add marketplace identifiers for EKS 1.30

- aws/aws-how-to/instances/launch-ubuntu-ec2-instance.rst
Just a small typo/discrepancy I noticed while reading through AWS's `launch-ubuntu-ec2-instance.rst`.
> Fix typo "Instantiate the image" on launch-ubuntu-ec2-instance.rst

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
Mantic is EOL as of 2024-07-11.
Listings are depreacated and not available
to subscribe.
> fix(ec2): Remove mantic product ids

- .sphinx/requirements.txt
- custom_conf.py
**Sample error**:
```
copying images... [100%] all-clouds-how-to/check-cve-on-instance-images/0_oscap_oval_cve_scan_report.png Exception occurred:
File "/xxx/ubuntu-cloud-docs/.sphinx/venv/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 780, in copy_image_files
self.srcdir / src, err)
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
**Occurs when** sphinx-multiproject extension is used and images are included in .rst files
**Fix**: Latest version of Sphinx expects 'srcdir' to be a Path, but the multiproject extension updates and returns 'srcdir' as a str.
A personal (temporary) fork of the multiproject extension was created with the required change and that is now specified in the custom_config.py as the extension to be used (instead of …
> Bug fix for sphinx related build errors.

- oci/oci-how-to/index.rst
Hi @k-dimple,
This is a really minor change mostly just to get myself acquainted with Canonical doc sets hosted in Git repos and published via RTD, and the process of editing them, as part of an onboarding exercise. Please help me review it whenever you can. I'd also appreciate any feedback/advice. Thank you.
> Fix minor typo in how-to index page

- azure/azure-explanation/index.rst
- azure/azure-explanation/security-features.rst
Discussions with respect to [0][1] determined that the full content of the Azure Security Overview document was unsuitable, as the majority of its content was non-specific to Azure and only reiterated security features and products core to Ubuntu - and not specific to Azure. Instead, merge the relevant sections (Ubuntu Security Features and Azure Security Features) into the existing security type document.
References:
[0] https://github.com/canonical/ubuntu-cloud-docs/pull/269
[1] https://warthogs.atlassian.net/browse/CPC-4950
> docs(azure): merge azure and ubuntu security features doc

- oracle/oracle-how-to/deploy-oke-nodes-using-ubuntu-images.rst
There are ongoing efforts to get VCN native CNI working with OKE, so the public docs should reflect that.
> feat(oracle): update oke support matrix for network-type

- .custom_wordlist.txt
- aws/aws-how-to/kubernetes/deploy-ubuntu-pro-cluster.rst
- aws/aws-how-to/security/use-secureboot-and-vtpm.rst
- public-images/index.rst
- public-images/public-images-explanation/index.rst
- public-images/public-images-explanation/lxd-openstack-images.rst
- public-images/public-images-explanation/vagrant.rst
- public-images/public-images-how-to/launch-with-libvirt.rst
- public-images/public-images-reference/artefacts.rst
Our public docs were missing explanations for our image offerings on [cloud-images.ubuntu.com](https://cloud-images.ubuntu.com) for LXD and OpenStack.
An "Explanation" index and landing page has been created on the `public-images` project now that there is more than one Explanation article.
A commit fixing the American spelling of `artifact` to the British spelling `artefact` across our docs is included in this PR as well.
> Add LXD and OpenStack image documentation

- .custom_wordlist.txt
- aws/aws-reference/index.rst
- aws/aws-reference/pro.rst
- aws/aws-reference/support.rst
This adds an overview for how to get support on AWS, including what Pro provides, AWS frontline support, and getting expanded support from Canonical
> feat(aws): add support options overview

- .custom_wordlist.txt
- aws/aws-explanation/canonical-offerings.rst
- aws/aws-reference/pro.rst
This adds a quick blurb on where Ubuntu Pro is on AWS.
> feat: add description on pro product availability

- oracle/oracle-how-to/deploy-oke-nodes-using-ubuntu-images.rst
VCN Native networking type is now available for OKE after squashing a long-term bug regarding udev and the kernel. The following changes reflect our support for all networking types offered by Oracle.
> feat(oke): VCN Native is now available for OKE

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
the current entry points to the jammy EKS 1.29 listings. a marketplace entry does not currently exist for focal EKS 1.29.
Fixes #307
> fix: remove focal EKS 1.29 marketplace entry

- google/google-how-to/gce/create-different-instance-types.rst
The doc previously gave steps to launch a jammy 22.04 instance, but we should encourage people to be up to date on LTSes
> Update create-different-instance-types.rst to encourage noble 24.04

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
24.04 EKS 1.31 listings are now available.
Update csv file with identifiers.
> fix: Add identifiers for 24.04 EKS 1.31 listings

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
- Ubuntu Pro 14.04 LTS
- Ubuntu 20.04 LTS for EKS 1.23 for AMD and ARM 
- Ubuntu 20.04 LTS for EKS 1.24 for AMD and ARM
> [AWS] Remove outdated marketplace listings

- .custom_wordlist.txt
- google/google-explanation/guest-agents.rst
- google/google-explanation/index.rst
Added a high-level description of each package, along with links to the upstream source code and the Ubuntu packages in LP.
> feat(GCE): Add documentation around the 4 Google guest agents

- all-clouds/conf.py
- aws/conf.py
- azure/conf.py
- google/conf.py
- ibm/conf.py
- oci/conf.py
- oracle/conf.py
- public-images/conf.py
As things move to matrix, document the new channel as a way to reach for community support.
> feat: add matrix channel to all clouds footers

- azure/azure-how-to/instances/find-ubuntu-images.rst
This commit adds a section to the Azure find-image how-to guide about the Jammy Pro FIPS (updates) image line that was recently introduced to the Azure Marketplace.
Refs: https://warthogs.atlassian.net/browse/CPC-5169
> feat(azure): Add Jammy Pro FIPS to find-images how-to guide

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
This adds references to EKS 1.32 marketplace listings for Ubuntu 22.04 and Ubuntu 24.04
> feat: add EKS 1.32 marketplace listings

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
this adds the new identifiers for fips-updates marketplace listings
> feat: add fips-updates 20.04, 22.04 identifiers

- oracle/oracle-how-to/find-ubuntu-images.rst
As per our chat @k-dimple - I tested out the commands on the page and found that the following needed updates to work on copy-paste.
Lmk if you have any issues with the changes - Thanks!
> fix(oracle): update oci launch commands on the find images how-to

- .custom_wordlist.txt
- aws/aws-how-to/kubernetes/deploy-self-managed-node-group.rst
- aws/aws-how-to/kubernetes/index.rst
This adds a small set of documentation to reference the upstream self-managed node group docs and specifying how to use eksctl to launch the node groups.
> feat: self-managed EKS ubuntu node groups

- azure/azure-explanation/security-features.rst
Changed the list of images that support CVMs to include every LTS from 20.04 onwards.
> [Azure] Update the explanation on security features

- all-clouds/conf.py
- all-clouds/index.rst
- aws/aws-how-to/instances/install-nvidia-drivers.rst
- aws/aws-how-to/instances/upgrade-to-ubuntu-pro-at-scale-using-tokens-with-ssm.rst
- aws/aws-reference/aws-announcements.rst
- aws/aws-reference/support.rst
- aws/conf.py
- aws/index.rst
- azure/azure-how-to/instances/create-pro-fips-golden-image.rst
- azure/azure-how-to/instances/index.rst
- azure/conf.py
- azure/index.rst
- custom_conf.py
- google/conf.py
- google/index.rst
- ibm/conf.py
- ibm/index.rst
- oci/conf.py
- oci/index.rst
- oracle/conf.py
- oracle/index.rst
- oracle/oracle-how-to/deploy-oke-nodes-using-ubuntu-images.rst
- public-images/conf.py
- public-images/public-images-explanation/vagrant.rst
- public-images/public-images-how-to/launch-qcow-with-qemu.rst
The links have now been permanently changed (discourse, server docs)
> Updated 'ua status' to 'pro status' and corrected a few links

- public-images/index.rst
- public-images/public-images-explanation/index.rst
- public-images/public-images-explanation/public-image-retention-policy.rst
Add section detailing our retention policy for public images when both LTS and Interim releases reach EOL/EOSS
> docs: document retention policy for download/public images

- .wordlist.txt
- all-clouds/all-clouds-how-to/install-proposed-nvidia-drivers-for-testing.rst
- all-clouds/index.rst
Tested the instructions by installing `cloud-init` from proposed since we don't have an update to NVIDIA drivers in proposed currently.
Rendered at: https://canonical-ubuntu-documentation-library--345.com.readthedocs.build/public-cloud/en/345/all-clouds-how-to/install-proposed-nvidia-drivers-for-testing/
> feat: Add docs to install NVIDIA drivers from proposed for testing

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
Focal is EOL soon so add the Pro based Focal EKS identifiers for the AWS Marketplace listings.
> feat(aws): add EKS-Pro Focal listings

- azure/azure-how-to/instances/find-ubuntu-images.rst
With 20.04 EOL, remove all non-pro 20.04 references from Azure documentation [0].
References:
[0] https://warthogs.atlassian.net/browse/CPC-7345
> feat(azure): remove non-pro 20.04 references

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
Focal is EOL and the Marketplace listings will soon be restricted so drop those from the docs.
> feat(aws): drop 20.04 non-Pro Marketplace entries

- azure/azure-how-to/instances/find-ubuntu-images.rst
This commit adds the new Specialized Hardware free and Pro image lines to the Azure find-images how-to.
Refs: https://warthogs.atlassian.net/browse/CPC-6438
@k-dimple Please do not merge this pull request until the first images have been published to the Marketplace. I will let you know when we have reached that point (likely by Monday morning).
> feat(azure): Add Specialized Hardware images to find-images how-to

- aws/aws-how-to/instances/aws-marketplace-identifiers.csv
EKS 1.33 listings and images are
published.
> fix: Add EKS 1.33 identifiers

- .readthedocs.yaml
- azure/azure-explanation/ubuntu-on-aks-worker-nodes.rst
The exact version that AKS uses is not clear from their [documentation](https://learn.microsoft.com/en-gb/azure/aks/node-images). So it is safer to just say Ubuntu like they do!
> Remove Ubuntu version from AKS worker nodes

- google/google-how-to/gce/upgrade-in-place-from-lts-to-pro.rst
Google is rolling out mutable licenses which allow changing the license
of the boot disk. Google has asked us to use this new mechanism for
in-place upgrades to Pro.
What current instructions describe is appending Pro license to the
`userLicenses` field of the boot disk, but not changing its `license`
field. The new approach modifies the `license` field.
In addition to describe new mechanisms, some style changes were made:
1. consistent variable references (FOO vs $FOO, and monospace)
2. formatting of lists
3. make the content below numbered list items actually belong to those
items
[1] https://community.cochrane.org/style-manual/formatting/lists
> feat(gce): Update Pro upgrade instructions

- aws/aws-how-to/instances/launch-ubuntu-desktop.rst
- oci/oci-explanation/ubuntu-oci-container.rst
- oci/oci-how-to/enable-pro-services.rst
- oci/oci-how-to/index.rst
Also correct a link which was getting redirected.
> Link to an external guide instead of copying content to avoid CI errors

- docs/conf.py
A link to the pro-clients docs was added when the copied content was removed. But anyone using the old link still needs to be redirected.
> Include a redirection link for the OCI how-to that was removed

- docs/azure/azure-how-to/instances/find-ubuntu-images.rst
This commit replaces the information concerning the now-end-of-life Oracular images with equivalent information for Plucky images.
Refs: https://warthogs.atlassian.net/browse/CPC-7953
> feat(azure): Replace Oracular with Plucky in find-images how-to

- docs/.custom_wordlist.txt
- docs/aws/aws-how-to/instances/find-ubuntu-images.rst
Our current documentation for finding EC2 images focuses solely on SSM parameters. while this is great for many use cases, there is a very large user base that prefers to use describe-images.
> feat(AWS) Add documentation on how to find images using describe-images

- docs/.sphinx/.wordlist.txt
- docs/public-images/public-images-how-to/index.rst
- docs/public-images/public-images-how-to/verify-image-checksum.rst
This PR adds a how-to page on using checksum to verify ISO images downloaded from https://cloud-images.ubuntu.com/
I referred the [Ubuntu docs](https://ubuntu.com/tutorials/how-to-verify-ubuntu#1-overview) to get started and added in my own code blocks and thoughts
I've attached a PDF version of the newly added page to view how the page is rendered
[Verify an image checksum.pdf](https://github.com/user-attachments/files/22663945/Verify.an.image.checksum.-.Ubuntu.Public.Images.documentation.pdf)
> feat(public-images): CPC-7526 Adding a how-to guide to verify an ISO image using checksum
